### ISSUE TITLE
syntax error appears after I install and connect rspec-parameterized gem

### ISSUE THREAD

**Issue by ruslanshelar** [tomykaira/rspec-parameterized#71]
Hello.

I have connected  rspec-parameterized gem according to instructions in read-me file.

But after it, I cannot run ant spec. I get the next errors:

```
/home/ruslan/.rvm/gems/ruby-2.0.0-p648/gems/unparser-0.4.7/lib/unparser.rb:116:in `require': /home/ruslan/.rvm/gems/ruby-2.0.0-p648/gems/unparser-0.4.7/lib/unparser/emitter/send/unary.rb:13: syntax error, unexpected ':', expecting ')' (SyntaxError)
          '-@': '-',
               ^
/home/ruslan/.rvm/gems/ruby-2.0.0-p648/gems/unparser-0.4.7/lib/unparser/emitter/send/unary.rb:13: syntax error, unexpected ',', expecting keyword_end
/home/ruslan/.rvm/gems/ruby-2.0.0-p648/gems/unparser-0.4.7/lib/unparser/emitter/send/unary.rb:14: syntax error, unexpected ':', expecting keyword_end
          '+@': '+'
               ^
/home/ruslan/.rvm/gems/ruby-2.0.0-p648/gems/unparser-0.4.7/lib/unparser/emitter/send/unary.rb:15: syntax error, unexpected ')', expecting keyword_end
        from /home/ruslan/.rvm/gems/ruby-2.0.0-p648/gems/unparser-0.4.7/lib/unparser.rb:116:in `<top (required)>'
        from /home/ruslan/.rvm/gems/ruby-2.0.0-p648/gems/rspec-parameterized-0.5.0/lib/rspec/parameterized.rb:3:in `require'
        from /home/ruslan/.rvm/gems/ruby-2.0.0-p648/gems/rspec-parameterized-0.5.0/lib/rspec/parameterized.rb:3:in `<top (required)>'
        from /home/ruslan/.rvm/gems/ruby-2.0.0-p648/gems/rspec-parameterized-0.5.0/lib/rspec-parameterized.rb:1:in `require'
        from /home/ruslan/.rvm/gems/ruby-2.0.0-p648/gems/rspec-parameterized-0.5.0/lib/rspec-parameterized.rb:1:in `<top (required)>'
        from /home/ruslan/RubymineProjects/git_referrals/spec/spec_helper.rb:2:in `require'
        from /home/ruslan/RubymineProjects/git_referrals/spec/spec_helper.rb:2:in `<top (required)>'
        from /home/ruslan/.rvm/gems/ruby-2.0.0-p648/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1455:in `require'
        from /home/ruslan/.rvm/gems/ruby-2.0.0-p648/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1455:in `block in requires='
        from /home/ruslan/.rvm/gems/ruby-2.0.0-p648/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1455:in `each'
        from /home/ruslan/.rvm/gems/ruby-2.0.0-p648/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1455:in `requires='
        from /home/ruslan/.rvm/gems/ruby-2.0.0-p648/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:112:in `block in process_options_into'
        from /home/ruslan/.rvm/gems/ruby-2.0.0-p648/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:111:in `each'
        from /home/ruslan/.rvm/gems/ruby-2.0.0-p648/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:111:in `process_options_into'
        from /home/ruslan/.rvm/gems/ruby-2.0.0-p648/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:21:in `configure'
        from /home/ruslan/.rvm/gems/ruby-2.0.0-p648/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:99:in `setup'
        from /home/ruslan/.rvm/gems/ruby-2.0.0-p648/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:86:in `run'
        from /home/ruslan/.rvm/gems/ruby-2.0.0-p648/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
        from /home/ruslan/.rvm/gems/ruby-2.0.0-p648/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
        from /home/ruslan/.rvm/gems/ruby-2.0.0-p648/gems/rspec-core-3.7.1/exe/rspec:4:in `<top (required)>'
        from /home/ruslan/.rvm/gems/ruby-2.0.0-p648/bin/rspec:23:in `load'
        from /home/ruslan/.rvm/gems/ruby-2.0.0-p648/bin/rspec:23:in `<main>'
        from /home/ruslan/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:22:in `eval'
        from /home/ruslan/.rvm/gems/ruby-2.0.0-p648/bin/ruby_executable_hooks:22:in `<main>'
```

ruby -v ruby 2.0.0p648 (2015-12-16 revision 53162) [x86_64-linux]
rails -v '3.2.15'

**Comment by joker1007** [comment]
Your ruby version is too old.
Sorry, this gem doesn't support the version.
Currently, this gem supports ruby-2.6.0 or later.
